version: "3.9"
services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: delovrukah-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: delovrukah
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d delovrukah"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
    driver: local
